# Site settings
baseURL = "https://www.hpcs.cs.tsukuba.ac.jp/~tsunashima/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Tsunashima, Ryuuta"
theme = "hugo-split-theme"
hasCJKLanguage = "true"
# disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Tsunashima, Ryuuta"

[params]

  # Metadata for search engines and social sharing
  # name = "Tsunashima Ryuuta"
  # description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  # shareImage = "images/social.jpg"
  # twitterHandle = "onepagelove"

  # Favicon
  # favicon = "favicon.ico"

  # Section - Content
  [params.content]
    name = "Tsunashima, Ryuuta"
    tagline = "Computer Scientist"
    bio = "Engineer. Programmer. Student of Master's Program in Computer Science."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/birthday.JPG"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "About me"
        url = "https://takashift.github.io/"

      [[params.links.list1.link]]
        text = "Blog(Technical)"
        url = "https://higechira.hatenablog.com/"

      [[params.links.list1.link]]
        text = "Blog(Miscellaneous)"
        url = "https://02yutori16.hatenablog.com/"

      [[params.links.list1.link]]
        text = "HPCS Lab."
        url = "https://www.hpcs.cs.tsukuba.ac.jp/"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter(Technical)"
        url = "https://twitter.com/higechira"

      [[params.links.list2.link]]
        text = "Twitter(Infomation)"
        url = "https://twitter.com/higechirakashit"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/ryutn"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://jp.linkedin.com/in/tnryu"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Job"

      [[params.links.list3.link]]
        text = "GitHub"
        url = "https://github.com/takashift"

      [[params.links.list3.link]]
        text = "Qiita"
        url = "https://qiita.com/higechira"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
